site_name: Regional DSGE

nav:
  - Home: index.md
  - Model:
      - Equilibrium: model/equilibrium.md
      #- Setup: model/setup.md
  - Policy:
      - Overview: policy/index.md
      - Innovation tax: policy/innovation-tax.md

theme:
  name: material


extra:
  generator: false
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
