site_name: Regional DSGE

nav:
  - Home: index.md
  - Model:
      - Equilibrium: model/equilibrium.md
  - Policy:
      - Overview: policy/index.md
      - Innovation tax: policy/innovation-tax.md

theme:
  name: material


extra:
  generator: false
